using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using DataAccess;
using BussinessLogic;
using System.Data;

public partial class Transactions_SalesChannel_PrimaryOrder : PageBase
{
    #region Page Load event
    protected void Page_Load(object sender, EventArgs e)
    {
        try
        {
            ucMsg.ShowControl = false;
            if (BackDaysAllowedOrder == 0)
            {
                ucDatePicker.Date = DateTime.Now.ToString();
                ucDatePicker.TextBoxDate.Enabled = false;
                ucDatePicker.imgCal.Enabled = false;
            }

            else
            {
                ucDatePicker.MinRangeValue = System.DateTime.Now.AddDays(-(BackDaysAllowedOrder));
                ucDatePicker.MaxRangeValue = System.DateTime.Now;
                ucDatePicker.RangeErrorMessage = "Invalid Date Range";

            }
            if (PageBase.IsIntermediaryOrderNoAutogenerate == 0)
            {
               
                txtOrderNo.Enabled = true;
            }
            else
            {
                
                txtOrderNo.Text = "Autogenerated";
                txtOrderNo.Enabled = false;
            }
            if (!IsPostBack)
            {
               
                FillParentsalesChannel();
            }
        }
        catch (Exception ex)
        {
            ucMsg.ShowError(ex.ToString(), PageBase.GlobalErrorDisplay());
            PageBase.Errorhandling(ex);
        }
    }
    #endregion
    #region User Defined Function
    void FillParentsalesChannel()
    {
        using (SalesChannelData ObjSalesChannel = new SalesChannelData())
        {

            ObjSalesChannel.SalesChannelID = PageBase.SalesChanelID;
            ObjSalesChannel.BlnShowDetail = true;
            string[] str = { "ParentId", "ParentName" };
            PageBase.DropdownBinding(ref ddlPsalesChannel, ObjSalesChannel.GetSalesChannelInfo(), str);
        };

    }
    bool pageValidateSave()
    {

        if (ddlPsalesChannel.SelectedIndex == 0 || txtOrderNo.Text.Trim() == string.Empty || ServerValidation.IsDate(ucDatePicker.Date, true) != 0)
        {
            ucMsg.ShowWarning(Resources.Messages.MandatoryField);
            return false;
        }

        //if (Convert.ToDateTime(ucDatePicker.Date) != DateTime.Now.Date)
        //{
        //    ucMsg.ShowWarning(Resources.Messages.EnterCurrentDate);
        //    return false;

        //}
        return true;
    }
    bool pageValidateGo()
    {
        if (ServerValidation.IsDate(ucDatePicker.Date) == false)
        {
            ucMsg.ShowWarning(Resources.Messages.InvalidDateEntered);
            return false;
        }
        //if (Convert.ToDateTime(ucDatePicker.Date) != DateTime.Now.Date)
        //{
        //    ucMsg.ShowWarning(Resources.Messages.EnterCurrentDate);
        //    return false;

        //}
        if (txtOrderNo.Text.Trim() == string.Empty)
        {
            ucMsg.ShowWarning(Resources.Messages.EnterInvoiceNo);
            return false;
        }
        return true;
    }
    void ClearForm()
    {

        ddlPsalesChannel.ClearSelection();
        ddlPsalesChannel.SelectedValue = "0";
        txtOrderNo.Text = "";
        ucDatePicker.Date = "";
        ddlPsalesChannel.Enabled = true;
        pnlGrid.Visible = false;
        if (PageBase.IsIntermediaryOrderNoAutogenerate == 0)
        {

            txtOrderNo.Text = "";
        }
        

    }
    #endregion
    #region Button Event
    protected void BtnSubmit_Click(object sender, EventArgs e)
    {
        try
        {
            if (!pageValidateGo())
            {
                return;
            }
            using (SalesData objSales = new SalesData())
            {
                objSales.SalesChannelID = PageBase.SalesChanelID;
                objSales.Brand = PageBase.Brand;
                objSales.InvoiceDate = Convert.ToDateTime(ucDatePicker.Date);
                DataTable dtOrder = objSales.GetOrderDetail();
                if (dtOrder != null && dtOrder.Rows.Count > 0)
                {
                    ddlPsalesChannel.Enabled = false;

                }
                else
                {


                    ddlPsalesChannel.Enabled = true;
                }
                Ucgrid.Salestype = EnumData.eControlRequestTypeForEntry.eOrder;
                Ucgrid.Source = dtOrder;

                pnlGrid.Visible = true;

            }
        }
        catch (Exception ex)
        {
            ucMsg.ShowError(ex.ToString(), PageBase.GlobalErrorDisplay());
            PageBase.Errorhandling(ex);
        }
    }
    protected void btnSave_Click(object sender, EventArgs e)
    {
        try
        {
            if (IsPageRefereshed == true)
            {
                return;
            }

            if (!pageValidateSave())
            {
                return;
            }
            Ucgrid.Salestype = EnumData.eControlRequestTypeForEntry.eOrder;
            DataTable Dt = Ucgrid.ReturnGridSource();
            string SumQTY = Dt.Compute("sum(Quantity)", "1=1").ToString();

            if (Dt == null || Dt.Rows.Count == 0 || SumQTY == "0")
            {
                ucMsg.ShowInfo(Resources.Messages.Entersalesqty);
                return;
            }
            DataTable DtDetail = new DataTable();
            using (CommonData ObjCommom = new CommonData())
            {
                DtDetail = ObjCommom.GettvpTableOrder();
            }

            foreach (DataRow dr in Dt.Rows)
            {
                DataRow drow = DtDetail.NewRow();
                drow[0] = 0;
                if (txtOrderNo.Text.ToLower() == "autogenerated")
                    drow[1] = "";
                else
                    drow[1] = txtOrderNo.Text;
               
                drow[2] = ucDatePicker.Date;
                drow[3] = PageBase.SalesChanelID;
                drow[4] = Convert.ToString(ddlPsalesChannel.SelectedValue);
                drow[5] = dr["SKUCode"].ToString();
                drow[6] = dr["Quantity"].ToString();
                DtDetail.Rows.Add(drow);
            }


            DtDetail.AcceptChanges();

            DtDetail = DtDetail.DefaultView.ToTable();
            if (DtDetail == null || DtDetail.Rows.Count == 0)
            {
                ucMsg.ShowInfo(Resources.Messages.Entersalesqty);
                return;
            }
            using (SalesData ObjSales = new SalesData())
            {

                ObjSales.Error = "";
                ObjSales.UserID = PageBase.UserId;
                ObjSales.InsertIntermediaryOrderInfo(DtDetail);

                if (ObjSales.Error != null && ObjSales.Error != "")
                {
                    ucMsg.ShowInfo(ObjSales.Error);
                    return;
                }


                ucMsg.ShowSuccess(string.Format("Order No. {0} created sucessfully", ObjSales.OrderNumber));
                pnlGrid.Visible = false;
                ClearForm();

            }
        }
        catch (Exception ex)
        {
            ucMsg.ShowError(ex.ToString(), PageBase.GlobalErrorDisplay());
            PageBase.Errorhandling(ex);
        }
    }
    protected void btnReset_Click(object sender, EventArgs e)
    {
        ucMsg.ShowControl = false;
        ClearForm();
    }
    #endregion

   
    
    
}
